server {
    listen 80;

    # ------------------------------------------------------------
    # ROUTE 1: WRITE OPERATIONS (Creation Service)
    # ------------------------------------------------------------
    # Matches requests starting with /api (e.g., POST /api)
    location /api {
        # Rate Limit: Apply strict throttling here (defined in nginx.conf)
        limit_req zone=api_limit burst=10 nodelay;

        proxy_pass http://creation-service:8082;
        
        # Standard Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ------------------------------------------------------------
    # ROUTE 2: READ OPERATIONS (Redirect Service)
    # ------------------------------------------------------------
    # Matches everything else (e.g., GET /AbCd12)
    location / {
        # No rate limit here (or a looser one) so users can click links freely
        
        proxy_pass http://redirect-service:8081;
        
        # Standard Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}