spring.application.name=creation-service

server.address=0.0.0.0
server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/url_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USER}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASS}

features.cache.enabled=true
features.async.post.enabled=true